### ISSUE TITLE
SQL database handling

### ISSUE THREAD

**Issue by robxu9** [Minequest/Minequest-Reloaded-Core#1]
Handle storage of players in an SQL database (sqlite or mysql, both queries should be the same)

**Comment by robxu9** [comment]
Made easier with 2f4ce11 - one SQL query per file, please.

**Comment by robxu9** [comment]
SQL Functions should be implemented ASAP:

in src/main/resources/sql, the following should be implemented (probably):

-- table: mq_players (folder: player)

> add new player (automatically given player ID)
> update player level
> update player exp
> update player class
> update player abilities

-- in "setup" folder

> setup_player_table.sql to setup player tables
> migration_0.sql to setup SQL migration from version 0

blocks #9 until finished.

**Comment by Echobob** [comment]
Yeah that's what I'm working on today

**Comment by Echobob** [comment]
What should the location be when using Sqlite?

**Comment by robxu9** [comment]
Should be getDataFolder()/minequest.db...

**Comment by robxu9** [comment]
We're done with this.
