### ISSUE TITLE
Instanced Dungeons

### ISSUE THREAD

**Issue by robxu9** [Minequest/Minequest-Reloaded-Core#10]
It looks like MineQuest is so deeply built around instanced dungeons, that this really has to become a core feature.

**Comment by robxu9** [comment]
A way to reenter/exit the dungeon should also be provided...

**Comment by Echobob** [comment]
dungeons run as separate world files. That sounds like it would eat more ram if they are saved so players can reenter

**Comment by robxu9** [comment]
Well, I meant while the Quest is running...? If everyone on the team has left or if nobody has entered the dungeon, or (in rare cases) you get a quest but don't start it, the world should not even exist...
(on server shutdown, all quest worlds should be gone...)

**Comment by Echobob** [comment]
yeah. if there is someone still active in the quest then sure.

**Comment by robxu9** [comment]
This needs to be tested now :|

**Comment by Echobob** [comment]
I will give it a shot when I get home :)
Well I will need to write a quest first.

**Comment by robxu9** [comment]
Try using some of the existing quests, like the dungeon quests. I need to make sure I have backwards compatibility as well :)

**Comment by Echobob** [comment]
Well that quest wasn't totally functional since .40 of the original MQ. I will give it a shot though. :)

**Comment by robxu9** [comment]
lol, didn't know that.

**Comment by Echobob** [comment]
It worked though. It just wasn't 100% function. Probably because MQ wasn't 100% functional. XD

**Comment by robxu9** [comment]
hehe xD well, time to make it close to 100% functional :D

**Comment by Echobob** [comment]
Minequest looks so pretty right now. So clean. No giant spam of errors when players join or leave. My players are anxious to  test it :).

**Comment by robxu9** [comment]
This is also done.
