### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by robxu9** [Minequest/Minequest-Reloaded-Core#11]
MineQuest commands

**Comment by Echobob** [comment]
How do you want players to join each other? Invites from the leader?

**Comment by robxu9** [comment]
Yup - that should work.

**Comment by Echobob** [comment]
Ok I will work on that then.

**Comment by robxu9** [comment]
I think I need to check the team code to see how teams are formed - that is, making adjustments in the case of one-player quests...

**Comment by Echobob** [comment]
Yeah Im a little confused how it works. How do I add a player to a team?

**Comment by robxu9** [comment]
with the method add(Player p) that returns a boolean denoting success.
Use TeamManager to create and remove teams, because Teams have IDs stuck to them...
(I think I'm going to change the constructor of Team to protected now...)

**Comment by Echobob** [comment]
I can't figure out how to add people to a team. Mind giving me a hand? (It's probably something stupid. My brain still fried from being sick)

**Comment by robxu9** [comment]
I haven't implemented that in TeamManager - I'll be doing that right now :)
(note to self: TeamManager needs to be unstaticized)

**Comment by Echobob** [comment]
Ok that helps  :D

**Comment by Echobob** [comment]
I have tested the commands. So far no problems have been found that I haven't already fixed.

**Comment by robxu9** [comment]
:D

**Comment by Echobob** [comment]
The only thing I didn't test is the actual accept invite command. Because no one would join my team. :(   Forever alone.

**Comment by Echobob** [comment]
I will test this as well. With my second account.

**Comment by robxu9** [comment]
forever alone D:
