### ISSUE TITLE
Quest List

### ISSUE THREAD

**Issue by Echobob** [Minequest/Minequest-Reloaded-Core#17]
This will be part of the sql files. Needs to be edited when ever a player hits a quest sign. Also will need to be read when the player types the /quest list command.

**Comment by robxu9** [comment]
Would it be simply ok to list all the quest files in a directory? We can also attribute issue #7 to provide more meaningful descriptions...

**Comment by Echobob** [comment]
sounds good to me

**Comment by robxu9** [comment]
When I tried with signs, this was malfunctioning :| I have yet to figure out why, hmm... blocks issue 10 until closed.

**Comment by Echobob** [comment]
Yes I tried as well. Same result. Maybe we should add something that breaks the sign if the quest is an incorrect name. That way we will be able to tell if it isn't picking up the first line or it is just not picking up the quest name.

**Comment by robxu9** [comment]
I tried that... I don't want it to break the sign right now. Too annoying to debug.

**Comment by Echobob** [comment]
Ok I will work on it and try different things. Maybe we should look at what other plugins do to see how it compares to ours.

**Comment by robxu9** [comment]
I think maybe the SQL queries aren't sticking to the database... I have to look closely though, I might be missing something that's right in front of my face.

**Comment by Echobob** [comment]
Lol its always something simple XD.

**Comment by Echobob** [comment]
We could add something that turns the text read if the quest is wrong. That could help in testing.

**Comment by robxu9** [comment]
This is done.
