### ISSUE TITLE
Quest ability to disable certain Abilities

### ISSUE THREAD

**Issue by robxu9** [Minequest/Minequest-Reloaded-Core#8]
Allow Quests to define which abilities shouldn't be available.

**Comment by Echobob** [comment]
Cool Idea

**Comment by Echobob** [comment]
Maybe we can make it just disable full classes. That way we can set what class should be able to do a quest.

**Comment by robxu9** [comment]
New QuestParser API provides for this. I will integrate into RPG ASAP.

**Comment by robxu9** [comment]
implemented.
